### ISSUE TITLE
multiuser docker-compose on same dev environment

### ISSUE THREAD

**Issue by danr** [pharmbio/imagedb#18]
Some issues found when Anders and Dan both ran docker-compose on the dev server.

The `anders` user is running the docker compose in the directories `cli` and `db`.
Then both `anders` and `dan` want to run `webserver`. The `dan` user does these changes:

0. Changes to `TRAEFIK_FRONTEND_END` in `.env`

1. Volumes: changing to make them to absolute directories:

    ```
    volumes:
      - /home/dan/imagedb/webserver:/app
      - /share/mikro:/share/mikro
      - /share/imagedb:/share/imagedb
    ```

2. Service and container name

    ```
    services:
      imagedbweb-dan:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: imageweb-dan
    ```

3. Traefik route name in under `label`:

    ```
      - "traefik.http.routers.imagedbweb-dan.rule=Host(`${TRAEFIK_FRONTEND_URL?You need to specify env TRAEFIK_FRONTEND_URL, e.g. TRAEFIK_FRONTEND_URL=name.my-domain.com}`)"
      - "traefik.http.routers.imagedbweb-dan.entrypoints=websecure"
      - "traefik.http.routers.imagedbweb-dan.tls.certresolver=myresolver"
    ```

4. Port exposed to `traefik`:

    ```
    ports:
      - 18092:8080
    labels:
      - "traefik.port=18092"
    ```
